-- 1. PRODUCTS
create table products (
    id bigint generated by default as identity primary key,
    name text not null,
    description text,
    price numeric(10,2) not null,
    stock integer not null default 0,
    container_size text not null,
    created_at timestamptz default now()
);

-- 2. PROFILES
create table profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    full_name text not null,
    phone text not null,
    address text not null,
    role text not null default 'user',
    created_at timestamptz default now()
);

-- 3. ORDERS
create table orders (
    id bigint generated by default as identity primary key,
    user_id uuid not null references profiles(id) on delete cascade,
    order_date timestamptz default now(),
    status text not null default 'pending',
    total_amount numeric(10,2) not null default 0,
    delivery_address text not null,
    created_at timestamptz default now()
);

-- 4. ORDER ITEMS
create table order_items (
    id bigint generated by default as identity primary key,
    order_id bigint not null references orders(id) on delete cascade,
    product_id bigint not null references products(id) on delete cascade,
    quantity integer not null,
    price numeric(10,2) not null
);
--5. Deliveries 
create table deliveries (
    id bigint generated by default as identity primary key,
    order_id bigint not null references orders(id) on delete cascade,
    employee_id uuid references profiles(id) on delete set null, -- no employee table set to null in defualt
    status text not null default 'assigned',
    delivery_date timestamptz,
    created_at timestamptz default now()
);
