-- WATER DELIVERY SYSTEM DATABASE SCHEMA

-- 1. PROFILES
CREATE TABLE public.profiles (
    id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    first_name text NOT NULL,
    last_name text NOT NULL,
    middle_initial text,
    phone text NOT NULL,
    address text NOT NULL,
    role text NOT NULL DEFAULT 'user',
    created_at timestamptz DEFAULT now()
);

-- 2. PRODUCTS
CREATE TABLE public.products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    description text,
    price numeric(10,2) NOT NULL,
    stock integer NOT NULL DEFAULT 0,
    container_size text NOT NULL,
    created_at timestamptz DEFAULT now()
);

-- 3. ORDERS
CREATE TABLE public.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    order_date timestamptz DEFAULT now(),
    status text NOT NULL DEFAULT 'pending',
    total_amount numeric(10,2) NOT NULL DEFAULT 0,
    delivery_address text NOT NULL,
    created_at timestamptz DEFAULT now()
);

-- 4. ORDER ITEMS
CREATE TABLE public.order_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    quantity integer NOT NULL,
    price numeric(10,2) NOT NULL
);

-- 5. DELIVERIES
CREATE TABLE public.deliveries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    employee_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    status text NOT NULL DEFAULT 'assigned',
    delivery_date timestamptz,
    created_at timestamptz DEFAULT now()
);
